### PR TITLE
Move contact page and api endpoint to routes folder.

### PR DESCRIPTION
**Pull request by blanxii**
Issue #36

### CODE REVIEW

**Comment by blanxii** [comment]
Hi @butlerx 

I tested URL: http://localhost:3000/about/contact/ and the /api/ endpoint and both are working (I try to /api/contact but I got Recaptcha error, but I saw the same error in master branch).

How can I test the entry flow?

**Comment by butlerx** [comment]
need to close #40 so as to test before merge

**Comment by butlerx** [comment]
@blanxii you did add keys for the recaptcha as there are no testing keys in the repo

**Comment by blanxii** [comment]
Yes tested with recaptcha keys and it's not working

**Comment by butlerx** [comment]
cool ill have a look and see if i can figure out what i broek

**Comment by VoyTechnology** [comment]
Added the `on hold` label until #40 is resolved as @butlerx said. Please remove when no longer blocked

**Comment by butlerx** [comment]
fix in #66 
more routes have been added since this was done

**Comment by butlerx** [comment]
#66 has been merged so this is no longer on hold

**Comment by butlerx** [comment]
@blanxii could you please rebase?

**Comment by butlerx** [comment]
closed in #113

**Pull request closed without merging**
