### PR TITLE
add codeclimate

### PR DESCRIPTION
**Pull request by butlerx**

### CODE REVIEW

**Comment by VoyTechnology** [comment]
Resolves #186

**Comment by butlerx** [comment]
id rather not commit the shrinkwrap file but nsp currently doesnt support the lockfile https://github.com/nodesecurity/nsp/issues/136

**Comment by VoyTechnology** [comment]
Can they be added in another PR? They seem unrelated to CodeClimate

**Comment by butlerx** [comment]
no its codeclimate thats requiring it

**Pull request merged**
