### PR TITLE
add process to generate thumbnails and banner images

### PR DESCRIPTION
**Pull request by butlerx**

### CODE REVIEW

**Comment by SeanHealy33** [comment]
😱 
screen shot 2016-10-12 at 17 16 34

**Comment by SeanHealy33** [comment]
I'm not convinced they should be stored in git tbh. Images arnt something I feel the source should care about

**Comment by butlerx** [comment]
This from the man who stores backgrounds in git :stuck_out_tongue: but in all seriousness yeah i get that think add to banner-* and thumb-* to gitignore?

**Comment by SeanHealy33** [comment]
Fair enough :smile: 

Git was the good solution to an Intercom wall paper transfer

**Pull request merged**
